# Generated by Django 4.1.7 on 2023-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_aiframework_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text_desc',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
